export const URL='http://192.168.106.100:5000/';
export const _URL_GET_USERS=URL+'getUsers';
export const _URL_AUTH=URL+'getAuth';
export const _URL_GET_RESULTADOS=URL+'getResultados';   // URL de la API para obtener los resultados de los usuarios
export const _URL_GET_MODULOS=URL+'getModulos';         // URL de la API para obtener los módulos
export const _URL_GET_PREGUNTAS_MODULO1=URL+'getPreguntas'; 
export const _URL_GET_PREGUNTAS_MODULO2=URL+'getPreguntas2';
export const _URL_GET_PREGUNTAS_MODULO3=URL+'getPreguntas3';    
export const _URL_GET_PREGUNTAS_MODULO4=URL+'getPreguntas4';
export const _URL_GET_PREGUNTAS_MODULO5=URL+'getPreguntas5';
export const _URL_GET_PREGUNTAS_MODULO=URL+'getPreguntas';